{{- if .Values.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "common.names.fullname" . }}-web-hpa
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    openproject/process: web
    app.kubernetes.io/component: web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "common.names.fullname" . }}-web
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.autoscaling.targetMemoryUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
  {{- range .Values.autoscaling.customMetrics }}
  - type: {{ .type }}
    {{- if eq .type "Pods" }}
    pods:
      metric:
        name: {{ .pods.metric.name }}
        {{- if .pods.metric.selector }}
        selector:
          {{- toYaml .pods.metric.selector | nindent 10 }}
        {{- end }}
      target:
        type: {{ .pods.target.type }}
        {{- if .pods.target.averageValue }}
        averageValue: {{ .pods.target.averageValue }}
        {{- end }}
        {{- if .pods.target.value }}
        value: {{ .pods.target.value }}
        {{- end }}
    {{- else if eq .type "Object" }}
    object:
      metric:
        name: {{ .object.metric.name }}
        {{- if .object.metric.selector }}
        selector:
          {{- toYaml .object.metric.selector | nindent 10 }}
        {{- end }}
      describedObject:
        apiVersion: {{ .object.describedObject.apiVersion }}
        kind: {{ .object.describedObject.kind }}
        name: {{ .object.describedObject.name }}
      target:
        type: {{ .object.target.type }}
        {{- if .object.target.value }}
        value: {{ .object.target.value }}
        {{- end }}
        {{- if .object.target.averageValue }}
        averageValue: {{ .object.target.averageValue }}
        {{- end }}
    {{- else if eq .type "External" }}
    external:
      metric:
        name: {{ .external.metric.name }}
        {{- if .external.metric.selector }}
        selector:
          {{- toYaml .external.metric.selector | nindent 10 }}
        {{- end }}
      target:
        type: {{ .external.target.type }}
        {{- if .external.target.value }}
        value: {{ .external.target.value }}
        {{- end }}
        {{- if .external.target.averageValue }}
        averageValue: {{ .external.target.averageValue }}
        {{- end }}
    {{- end }}
  {{- end }}
  {{- with .Values.autoscaling.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}