{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "common.names.fullname" . }}-metrics
  {{- if .Values.metrics.serviceMonitor.namespace }}
  namespace: {{ .Values.metrics.serviceMonitor.namespace | quote }}
  {{- else }}
  namespace: {{ include "common.names.namespace" . | quote }}
  {{- end }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: openproject
  {{- with .Values.metrics.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  endpoints:
  - port: metrics
    path: {{ .Values.metrics.path }}
    interval: {{ .Values.metrics.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
    honorLabels: {{ .Values.metrics.serviceMonitor.honorLabels }}
    {{- if .Values.metrics.serviceMonitor.metricRelabelings }}
    metricRelabelings:
      {{- toYaml .Values.metrics.serviceMonitor.metricRelabelings | nindent 6 }}
    {{- end }}
    {{- if .Values.metrics.serviceMonitor.relabelings }}
    relabelings:
      {{- toYaml .Values.metrics.serviceMonitor.relabelings | nindent 6 }}
    {{- end }}
  jobLabel: {{ include "common.names.fullname" . }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
{{- end }}