---
apiVersion: "v2"
name: "openproject"
description: "A Helm chart for running OpenProject via Kubernetes"
home: "https://www.openproject.org/"
icon: "https://www.openproject.org/assets/images/press/openproject-icon-original-color-41055eb6.png"
type: "application"
version: "0.0.0"
appVersion: "12.4.0"
dependencies:
  - name: "postgresql"
    repository: "https://charts.bitnami.com/bitnami"
    version: "^12.1.6"
    condition: "postgresql.bundled"
  - name: "memcached"
    repository: "https://charts.bitnami.com/bitnami"
    condition: "memcached.bundled"
    version: "^6.3.2"
  - name: "common"
    repository: "https://charts.bitnami.com/bitnami"
    version: "^2.2.2"
...
