# values to use for a local development setup

develop: true

image:
  # using openproject/openproject:dev
  tag: dev

ingress:
  enabled: true
  tls:
    # using http locally for simplicity
    enabled: false
  # use any host name pointing to localhost, like *.openproject-dev.com does
  host: helm.openproject-dev.com

openproject:
  useTmpVolumes: true
  realtime_collaboration:
    hocuspocus:
      # not using TLS locally for simplicity
      protocol: ws

persistence:
  accessModes:
    # On a real cluster this would not do because web and worker pods couldn't access the same volumes.
    # However, on a local development cluster you usually only have one node.
    # And 'ReadWriteOnce' allows all pods on the same node to read/write on the same volume with this accessMode.
    - "ReadWriteOnce"
